[package]
name = "chat-rusty"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
shuttle-rocket = "0.46.0"
shuttle-runtime = "0.46.0"

[dev-dependencies]
rand = "0.8"